### ISSUE TITLE
data source question

### ISSUE THREAD

**Issue by justinelliotmeyers** [OpenUpSA/wazimap-ng-boundaries#1]
hey! Just found these awesome boundaries!! What is the source?  Thank you!
Justin

**Comment by jbothma** [comment]
Hi!

https://www.demarcation.org.za/
https://dataportal-mdb-sa.opendata.arcgis.com/

I'll put it in the README - thanks for asking!

You can also find some at https://github.com/OpenUpSA/SA-Maps which also
come from MDB. This wazimap repo just has some particular formatting.

JD

**Comment by justinelliotmeyers** [comment]
JD

Thank you! I believe new boundaries will be completed/ updated after the November election as well. Can you confirm?

Cheers,
Justin

**Comment by jbothma** [comment]
According to the response I received from my mail to info@demarcation.org.za, the 2020 wards shapefile (https://dataportal-mdb-sa.opendata.arcgis.com/datasets/e0223a825ea2481fa72220ad3204276b/about) is the correct one to use for wards, which takes effect after the local government elections on 1 November. 

I think it's just called 2020 because the process of public consultation and confirmation took place in 2020. That matches up with the message accompanying the gazettes from the time

![Screenshot_2021-10-14_20-57-11](https://user-images.githubusercontent.com/235801/137384272-5ea84e76-7c5b-4627-8cb7-7de8b10f4369.png)

**Comment by jbothma** [comment]
Readme updated. Thanks for the enquiry!

I'd love to hear what you use these boundaries for, if you don't mind sharing!
